server:
  port: 9991

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    # mysql driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc:db종류://host주소:초드/DB이름
    url: jdbc:mysql://localhost:3306/search_region
    username: root
    password: 1234

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE